import { useState } from "react";
import { Link, NavLink } from "react-router";
import { ArrowUpRight, Menu } from "./icons";
export function Logo() { return <Link className="logo" to="/"><span className="logo-mark">◒</span><span>bilatec<span className="logo-dot">.</span></span></Link>; }
export function Nav() { const [open, setOpen] = useState(false); const links = [["/solutions", "Solutions"], ["/projects", "Projects"], ["/about", "About"], ["/contact", "Contact"]]; return <header className="nav-wrap"><nav className="nav"><Logo /><div className={`nav-links ${open ? "is-open" : ""}`}>{links.map(([to, label]) => <NavLink key={to} to={to} onClick={() => setOpen(false)}>{label}</NavLink>)}<ButtonLink to="/contact" onClick={() => setOpen(false)}>Get an estimate <ArrowUpRight /></ButtonLink></div><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><Menu /></button></nav></header>; }
export function ButtonLink({ to, children, variant = "yellow", onClick }: { to: string; children: React.ReactNode; variant?: "yellow" | "dark"; onClick?: () => void }) { return <Link onClick={onClick} className={`button button-${variant}`} to={to}>{children}</Link>; }
export function PageIntro({ label, title, copy }: { label: string; title: React.ReactNode; copy: string }) { return <div className="page-intro reveal-up"><p className="eyebrow">{label}</p><h2>{title}</h2><p>{copy}</p></div>; }
export function Stat({ number, label }: { number: string; label: string }) { return <div className="stat"><strong>{number}</strong><span>{label}</span></div>; }
export function Testimonial() { return <section className="quote-section"><div className="quote-mark">“</div><blockquote>Bilatec made the biggest upgrade to our home feel surprisingly human. We know where our power comes from now, and that feels good.</blockquote><div className="quote-person"><div className="avatar">JM</div><span><strong>Julia & Mark</strong><small>Bilatec homeowners, Portland</small></span></div></section>; }
export function Footer() { return <footer className="footer"><div className="footer-top"><div><Logo /><p>Power, reimagined for<br />the way you live.</p></div><div className="footer-links"><div><span>Explore</span><Link to="/solutions">Solutions</Link><Link to="/projects">Projects</Link><Link to="/about">Our story</Link></div><div><span>Reach out</span><Link to="/contact">Start a project</Link><a href="mailto:hello@bilatec.com">hello@bilatec.com</a><a href="tel:+18002452832">1 800 BILATEC</a></div></div><div className="footer-cta"><p>Ready to make<br /><em>your own sunshine?</em></p><ButtonLink to="/contact">Let&apos;s talk <ArrowUpRight /></ButtonLink></div></div><div className="footer-bottom"><span>© 2026 Bilatec Energy</span><span>Made for a brighter tomorrow <b>✦</b></span><span>Instagram &nbsp; LinkedIn</span></div></footer>; }